name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
env:
  AWS_REGION: us-east-1
  TF_EXECUTION_PLAN_FILE_NAME: execution-plan

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: infrastructure/terraform
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Terraform version
        id: get_version
        run: echo "TERRAFORM_VERSION=$(cat .terraform.version)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ steps.get_version.outputs.TERRAFORM_VERSION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform plan
        run: terraform plan -out=${{ env.TF_EXECUTION_PLAN_FILE_NAME }}

      - name: Upload execution plan artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TF_EXECUTION_PLAN_FILE_NAME }}
          path: ${{ env.TF_EXECUTION_PLAN_FILE_NAME }}

      - name: Provision the new resources
        run: terraform apply ${{ env.TF_EXECUTION_PLAN_FILE_NAME }}
  
  deploy-app:
    needs: deploy-infrastructure
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.24.2
        with:
          workflow: ci.yml
          name: build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}
        
      - name:  Sync the build folder with S3
        run: |
          aws s3 sync . s3://${{ secrets.BUCKET_NAME }}