name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.24.2
        with:
          github_token: 'test'
          workflow: ci.yml
          name: build
        
      - name: Display structure of downloaded files
        run: ls -R build
