name: Continuos Integration

on: [pull_request, workflow_dispatch]

env:
  AWS_REGION: us-east-1
  TF_FOLDER_PATH: infrastructure/terraform
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  paths_filter:
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      pull-requests: read
    outputs:
      app: ${{ steps.filter.outputs.app }}
      infrastructure: ${{ steps.filter.outputs.infrastructure }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup paths filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          app:
            - '!infrastructure/**'
          infrastructure:
            - '${{ env.TF_FOLDER_PATH }}/**'

  infrastructure:
    runs-on: ubuntu-22.04
    needs: paths_filter
    if: ${{ needs.paths_filter.outputs.infrastructure == 'true' }}
    permissions:
      actions: read
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.TF_FOLDER_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Terraform plugin cache directory
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/terraform/.terraform.lock.hcl') }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: Get Terraform version
        id: get_tf_version
        run: echo "TF_VERSION=$(cat .terraform.version)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: ${{ steps.get_tf_version.outputs.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan

  application:
    runs-on: ubuntu-22.04
    needs: paths_filter
    if: ${{ needs.paths_filter.outputs.app == 'true' }}
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      
      - name: Vulnerability assessment of dependencies
        run: npm audit --audit-level=critical
      
      - name: Install Dependencies       
        run: npm ci --no-audit    
      
      - name: Lint code
        run: npm run lint
      
      - name: Unit testing
        run: npm test
      
      - name: Build
        run: npm run build
    
    
      

      
